---
- block:
    - name: "{{ aws_type[0] | default('') }} | Terraform Plan"
      terraform:
        project_path: "/root/mzc-sa-aws_iac/terraform/{{ aws_type[0] | default('') }}"
        plan_file: terraform.plan
        state: planned
      delegate_to: localhost

    - name: "{{ aws_type[0] | default('') }} | Terraform Apply"
      terraform:
        project_path: "/root/mzc-sa-aws_iac/terraform/{{ aws_type[0] | default('') }}"
        state: present
      delegate_to: localhost

  rescue:
    - name: "{{ aws_type[0] | default('') }} | Terraform Failure Message"
      debug:
        msg: '################### FAILED ###################'
      delegate_to: localhost
