---
- name: 'Packer | Create AWS AMI'
  hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: 'Validate Packer AMI'
      tags: [ paker, packer_validate ]
      shell:
        cmd: 'packer validate ami_was.json'
        chdir: '/root/mzc-aws-provisioning/packer/EC2-AMI/'
      args:
        executable: '/bin/bash'
      delegate_to: localhost
      register: validate_result
      changed_when: false

    - name: 'Build Packer AMI'
      tags: [ packer, packer_build ]
      shell:
        cmd: 'packer build ami_was.json'
        chdir: '/root/mzc-aws-provisioning/packer/EC2-AMI/'
      args:
        executable: '/bin/bash'
      delegate_to: localhost
      register: build_result
      changed_when: false
      when:
        - validate_result.rc == 0
