---
- name: 'WAS Server Configuration (Apache + PHP)'
  hosts: all
  become: yes
  gather_facts: false
  tasks:
    - block:
        - name: 'Install | Apache,PHP Web Service'
          yum:
            name: "{{ packages }}"
            state: 'present'
          vars:
            packages:
            - httpd
            - php
            - mysql
            - php-mysql

        - name: 'Add | PHP Source Files'
          shell: |
            echo -e "<?php\nphpinfo();\n?>" > /var/www/html/info.php
            if [ ! -f /var/www/html/ec2-linux-web.tar.gz ]; then
               cd /var/www/html
               wget https://for-distribution-cwk.s3-ap-northeast-2.amazonaws.com/ec2-linux-web.tar.gz
               tar xvfz ec2-linux-web.tar.gz
            fi
            yum -y update
          args:
            executable: '/bin/bash'
          changed_when: false

        - name: 'Add | DB Source Files'
          shell: |
            echo -e "<?php
            $servername = "abc-aurora-cluster.cluster-crm2u1irmmgo.ap-northeast-2.rds.amazonaws.com";
            $username = "admin";
            $password = "cdnadmin";
            $db = "abcdb";
            // Create connection
            $conn = mysqli_connect($servername, $username, $password);
            // Check connection
            if (!$conn) {
              die("Connection failed: " . mysqli_connect_error());
            }
            echo 'Installation Success! & Aurora Connection Success!';
            ?>" > /var/www/html/database.php
          args:
            executable: '/bin/bash'
          changed_when: false

        - name: 'Enable | Apache Web Service'
          systemd:
            name: 'httpd'
            state: started
            enabled: true

        - name: 'Check | Apache Web Service'
          wait_for:
            port: '80'
            delay: 0
            timeout: 1
            state: started

        - name: 'Playbook successful message'
          debug:
            msg: '################### SUCCESSFUL ###################'

      rescue:
        - name: 'Playbook failure message'
          debug:
            msg: '################### FAILED ###################'
